http:
  listener:
    host: "0.0.0.0"
    port: "8095"
    basepath: "/"
    protocol: "HTTP"
    timeout: "100000"
  process_config:
    host: "0.0.0.0"
    port: "8093"
    basepath: "/api/"
    protocol: "HTTP"
    timeout: "100000"
    client_id: "faf816533d73478cbb62430f1b8f8fbc"
    client_secret: "D2A34cfB74774EfA9ae101Ace3Bd8305"
    token_url: "http://apdev-oauth.us-e2.cloudhub.io/token"
    
email:
  host: "smtp.gmail.com"
  port: "587" 
  user: "testdpdemail@gmail.com"
  pass: "testserver"
  
api:
  id: "17586521"
  