http:
  exp_config:
    host: "0.0.0.0"
    port: "8095"
    basepath: "/api/"
    protocol: "HTTP"
    timeout: "100000"
    client_id: "b293a42021da47939c46177a9ae309dc"
    client_secret: "300884d0db584bC7B6a821484E6CAF5f"
    token_url: "http://apdev-oauth.us-e2.cloudhub.io/token"
    
email:
  host: "smtp.gmail.com"
  port: "587" 
  user: "testdpdemail@gmail.com"
  pass: "testserver"
  
  