http:
  orders_listener:
    host: "0.0.0.0"
    port: "8091"
    basepath: "/"
    protocol: "HTTP"
    timeout: "30000"
  order_item_listener:
    host: "0.0.0.0"
    port: "8092"
    basepath: "/"
    protocol: "HTTP"
    timeout: "30000"
api:
  id: "17578623"
  
db:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: ""
  db_name:  "orders"
  
email:
  host: "smtp.gmail.com"
  port: "587" 
  user: "testdpdemail@gmail.com"
  pass: "testserver"